a=input("enter the value of a")
b=input("enter the value of b")
c=int(a)+int(b)
print(c)
a=int(input("enter the value of a"))
b=int(input("enter the value of b"))
c=a+b
print(c)
a=input("enter the value of a")
b=input("enter the value of b")
c=int(a)-int(b)
print(c)
a=input("enter the value of a")
b=input("enter the value of b")
c=int(a)*int(b)
print(c)
a=input("enter the value of a")
b=input("enter the value of b")
c=int(a)/int(b)
print(c)
